name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: 92.42.96.175
          username: root
          key: ${{-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA5H7exE3PCRGN1+QUQ9auyNfUly0SY/pCmfg/6wNWJOspIgH4t+mk
hRqXT8GlRVkG7OjxEpPGdEjw9+y1k8Ec3BPQQVOv7EUyaxFe5q7dW0K7HWkjhHRu9/hP+j
RPOUxOW2SxeEab5aDTSDEE5yGNCl/m/6VNv2fBMIiqqp7Y7ci2H1NMspIfOzmmMZ2Zu1Eb
HzMyYPVjOQ37heCDTgmbf8BqDn1FwRIXcfTU6cdOGhpPDnMDSnZUyNqgY1wlS+9/xuVW/x
adMEHnMTAquuprRwrXwGdNuHLWtnKUQRYepo2vhqcEJrNVre2NTiuzMOZrbIMUVRtTdiWv
im8PcVzaLEbITGWXbQW+ocU3KUvUYmcszczSrxHOmvpqI42okRj8YuIOS9m6wjWDkJlpPh
QQp/DS1h/g/TEnzrJklcDWNCkpbzO26yZ3oRPho/wkB/Y55U9N4bLyHnFTU5oY8gRcfXBN
yp/yhxcS0q4qyqOU8WkhN0WHs7RxNmO1iCVx77cSwitcdkjTpq2vWB/aeJ8lJQGMhZWF71
89m9PRwRM1baRATURqKggUyGRP5igAORql+4UNqXdxmZ82C2HTefSxq5mrf0pj4RDfJY7W
GbcvAXG5X3TewM7FsiHlk1ZMriTe3g3Y1TnzTZbJI/F/9+d7hAz/EPYudwaHgjD8iyUNwi
kAAAdYWUlz2VlJc9kAAAAHc3NoLXJzYQAAAgEA5H7exE3PCRGN1+QUQ9auyNfUly0SY/pC
mfg/6wNWJOspIgH4t+mkhRqXT8GlRVkG7OjxEpPGdEjw9+y1k8Ec3BPQQVOv7EUyaxFe5q
7dW0K7HWkjhHRu9/hP+jRPOUxOW2SxeEab5aDTSDEE5yGNCl/m/6VNv2fBMIiqqp7Y7ci2
H1NMspIfOzmmMZ2Zu1EbHzMyYPVjOQ37heCDTgmbf8BqDn1FwRIXcfTU6cdOGhpPDnMDSn
ZUyNqgY1wlS+9/xuVW/xadMEHnMTAquuprRwrXwGdNuHLWtnKUQRYepo2vhqcEJrNVre2N
TiuzMOZrbIMUVRtTdiWvim8PcVzaLEbITGWXbQW+ocU3KUvUYmcszczSrxHOmvpqI42okR
j8YuIOS9m6wjWDkJlpPhQQp/DS1h/g/TEnzrJklcDWNCkpbzO26yZ3oRPho/wkB/Y55U9N
4bLyHnFTU5oY8gRcfXBNyp/yhxcS0q4qyqOU8WkhN0WHs7RxNmO1iCVx77cSwitcdkjTpq
2vWB/aeJ8lJQGMhZWF7189m9PRwRM1baRATURqKggUyGRP5igAORql+4UNqXdxmZ82C2HT
efSxq5mrf0pj4RDfJY7WGbcvAXG5X3TewM7FsiHlk1ZMriTe3g3Y1TnzTZbJI/F/9+d7hA
z/EPYudwaHgjD8iyUNwikAAAADAQABAAACAACD/ETxX4CX3GvyqOyLwxZzLTi/mmllFsoh
5iQFvIemC7BW1Iy2r185A4MjrteolyRI9MVL1dBsmzWWAEVic8oX1doV4iFceRwGfKI03g
0/CezLsE+z0w3GbsjD3jNlBY69fAyHTUIAAkYJDUenutmdhIgKY5HlXilZv5fVtqvXrniE
37kN7RndPA+j2UVTziW8f/Y5y4TlEA6Z5nXyPdp0kNCyTepc+/ZO/P1/jICw00GXNxhPis
quupqqyi9BDbbhTNhTwNxLY8YHw6rrDT2qa7j0ird6M9uSx9ybPAu4aV9aiF79e9mh/fYB
kXyQYojqxUyZXI95T4t2i3CAKwJaOZ90uIzU4DwcMVh6QLEkIM6tpZXcWGqtKspj8Zg8rN
i5mcDSDLE0wYtRwVkxj+M2jmj0ev0tERv0hw8htGsXR/zDdrU6Pdvs+crwfTEtVxZDq2/w
H+gZs7MP/4S71wWhsVdsUh9CcfH0I9jAfOEIlkV7gC3BEluBt/6ur9wcLV+KoKi7pS+pRC
7/IOgh2W/nfPyVvODwXqcebybuZPt566o4nGWLuO0QesA6U9ENzUp8qTCpuMkKvXurByx1
hx/a1yQOzZyVvC+ielq4nMyhEuRWU3/9I3N8QEnY07uJVdl1C8kSIRjwGzXE27fIscQzfe
Hgz3H2dUlHYaZBCyNhAAABAQCebAmQKxK9Rn6CswkE8okru6FsPLiDUERXe0ePNChw9oS6
CK9TP7hqPSbsP6s3pZGn6SKMwqkxq9L+eAWvnXfct9kgh1AXZAu95+fBdqOtmhrsd6uwfv
h4iHoAi3WZNAh9llN4t7pN4J1IFe8uzoBe5V+OgSNvhdGl9rn7Vh36xtWwp8BJhhWGwbOj
mSXi12cbU9DYmHPxYtzfwoRya5qj3xGMTZk+c//qJdZyvgwahAq7GKdlLqoZTvNmxeqsPr
eH6wbKjlOkFMJAzs5kmlrhkdedLBbSSaX/C9BcMSnmH7q27jW8GU2TU8qoQjj/jG+etbgu
zARtwg/XeOjJPnY7AAABAQDyDU/QXkp037jVuHIn84LUmYpxLs82KN2uAmQy4z3Mmv9/T2
YBnsM3i52mAB22su97S/coywKBw8+C+t8aBNs+Mb0kMKagVQjHqDZP7d68/NWtNjv9ws9h
Be7EFBOfGJ2uAvgGYn/k3hK5dzjkgHTto53DN/bT91JBv2ydUPoNgkj63jud+9F38OA7OA
TaLNuLS8A2Jzef2OuXKhOuvltaMmaihZJDU6OsYEfzbMMBSBcUrRDbAeaMA81rA4hVJ3Qf
k0j95OO5Livddg8xKiHRv6PhuIvDCVjxlK2vcl9OAqQzUN7EXOhtwYkLE8T5iTs3YUX3EE
S+RCyHfEHgjj6JAAABAQDxqZPmXMAEGLZsbw5lJ2MFkoQkAHrrZaXIPhlnWQeGOwrA6r87
2OcPtndNJGZqpHB+1dZIVRz+9uTDnxrSAtLWfZGvfiVzKJSwQV2arAb6BpBhCkK0zfj3HR
ymRWMTrDpGV5sjHTKTcplKF4Qu8rDo5LOnr5gWmVmBY/44NFqoFBkbXxe7pVBsVDGsGvfD
Hl3uwnvXUW2GibZcpVBCo9+ahtbKXzx1YoNyyrAH6729BDxhWw7q3L2iaLePpcSyONZf6v
HMGC1ul+HSSWhIF+5X4MjUkTZSK1zzQBCD3/REVtm8rkeKSXUJnLQZu18Coi5rb7V0tkj0
hLWrW0OGCX6hAAAAH3Jvb3RAdm0xNTkxNzQ1LnZkcy5hczIxMDU0Ni5uZXQBAgM=
-----END OPENSSH PRIVATE KEY-----}} # Это нужно добавить в Secrets на GitHub
          script: |
            cd ~/XRay-bot
            git pull origin main
            # Перезапуск бота (замени на свою команду, если она другая)
            pkill -9 -f python3
            nohup python3 src/app.py > bot.log 2>&1 &
